pipeline {
    agent any
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage('Checkout') {
            steps {
               git branch: 'main', credentialsId: 'a5e96ed7-3eac-47e3-aaa0-8b2a8dc0dc36', url: 'https://github.com/madhanshiva/sample'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker_id', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        echo 'Build Docker Image with Buildx'
                        docker buildx create --use
                        docker buildx build -t mvmadhan/cicd-e2e:${BUILD_NUMBER} -f python-jenkins-argocd-k8s/Dockerfile .
                        '''
                    }
                }
            }
        }

        stage('Push the artifacts') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker_id', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        echo 'Push to Repo'
                        docker buildx build -t mvmadhan/cicd-e2e:${BUILD_NUMBER} --push -f python-jenkins-argocd-k8s/Dockerfile .
                        '''
                    }
                }
            }
        }
    }
}
